const fs = require("fs");
const path = require("path");
const { ethers, network } = require("hardhat");

function buildConfig(overrides) {
  return {
    mode: "onchain",
    simulationReason: "",
    deployerAddress: "",
    deployerBalanceEth: "0",
    minRequiredBalanceEth: "0",
    walletFundingEth: "0",
    rpcUrl: process.env.SEPOLIA_RPC_URL || "https://ethereum-sepolia-rpc.publicnode.com",
    chainId: 11155111,
    explorerBaseUrl: "https://sepolia.etherscan.io/tx/",
    contracts: {
      mockUsdc: "",
      attackSimulator: "",
      agentGuardOnChain: "",
    },
    demoWallets: {
      alex: { address: "", privateKey: "" },
      sam: { address: "", privateKey: "" },
      attacker: { address: "", privateKey: "" },
      benignRecipient: "",
    },
    initialAmount: "50",
    drainAmount: "20",
    tokenDecimals: 6,
    ...overrides,
  };
}

function writeFrontendConfig(config) {
  const configText = `// Auto-generated by contracts/scripts/deployDemo.js\nexport const DEMO_CONFIG = ${JSON.stringify(
    config,
    null,
    2
  )};\n\nexport const ATTACK_SIMULATOR_ABI = [\n  \"function drainWallet(address token,address victim,address to,uint256 amount) external\",\n];\n\nexport const AGENT_GUARD_ONCHAIN_ABI = [\n  \"function approveIntent(address token,address to,uint256 amount) external\",\n  \"function validateAndExecute(address token,address to,uint256 amount) external\",\n  \"function intentHashOf(address user) external view returns (bytes32)\",\n];\n\nexport const MOCK_USDC_ABI = [\n  \"function balanceOf(address account) external view returns (uint256)\",\n  \"function allowance(address owner,address spender) external view returns (uint256)\",\n  \"function approve(address spender,uint256 amount) external returns (bool)\",\n  \"function decimals() external view returns (uint8)\",\n];\n`;

  const frontendConfigPath = path.resolve(__dirname, "../../frontend/src/agentguard.config.js");
  fs.writeFileSync(frontendConfigPath, configText, "utf8");
  return frontendConfigPath;
}

async function waitForEth(provider, address) {
  for (let i = 0; i < 20; i += 1) {
    const bal = await provider.getBalance(address);
    if (bal > 0n) {
      return;
    }
    await new Promise((r) => setTimeout(r, 1500));
  }
  throw new Error(`Timed out funding wallet ${address}`);
}

async function main() {
  const signers = await ethers.getSigners();
  const deployer = signers[0];

  if (!deployer) {
    // Non-blocking fallback mode for teams without a funded Sepolia deployer key.
    const alex = ethers.Wallet.createRandom();
    const sam = ethers.Wallet.createRandom();
    const attacker = ethers.Wallet.createRandom();
    const benignRecipient = ethers.Wallet.createRandom();

    const cfg = buildConfig({
      mode: "simulation",
      simulationReason: "missing_deployer_key",
      contracts: {
        mockUsdc: "",
        attackSimulator: "",
        agentGuardOnChain: "",
      },
      demoWallets: {
        alex: { address: alex.address, privateKey: "" },
        sam: { address: sam.address, privateKey: "" },
        attacker: { address: attacker.address, privateKey: "" },
        benignRecipient: benignRecipient.address,
      },
    });

    const target = writeFrontendConfig(cfg);
    console.log("No deployer key found. Generated simulation config instead of on-chain deploy.");
    console.log("Frontend config written:", target);
    return;
  }

  const provider = deployer.provider;
  const deployerBalance = await provider.getBalance(deployer.address);
  const walletFundingEth = process.env.DEMO_WALLET_FUNDING_ETH || "0.00035";
  const deployGasReserveEth = process.env.DEMO_DEPLOY_GAS_RESERVE_ETH || "0.0015";
  const fundingAmount = ethers.parseEther(walletFundingEth);
  const deployGasReserve = ethers.parseEther(deployGasReserveEth);
  const fundedWalletCount = 2n; // Alex + Sam need ETH to sign transactions. Attacker only receives tokens.
  const minRequiredBalance = fundingAmount * fundedWalletCount + deployGasReserve;

  console.log("Deploying live demo with:", deployer.address);
  console.log("Network:", network.name);
  console.log("Deployer balance (ETH):", ethers.formatEther(deployerBalance));
  console.log("Wallet funding per signer (ETH):", walletFundingEth);
  console.log("Minimum recommended deploy balance (ETH):", ethers.formatEther(minRequiredBalance));

  const alex = ethers.Wallet.createRandom();
  const sam = ethers.Wallet.createRandom();
  const attacker = ethers.Wallet.createRandom();
  const benignRecipient = ethers.Wallet.createRandom();

  if (deployerBalance < minRequiredBalance) {
    const cfg = buildConfig({
      mode: "simulation",
      simulationReason: "insufficient_funds",
      deployerAddress: deployer.address,
      deployerBalanceEth: ethers.formatEther(deployerBalance),
      minRequiredBalanceEth: ethers.formatEther(minRequiredBalance),
      walletFundingEth,
      demoWallets: {
        alex: { address: alex.address, privateKey: "" },
        sam: { address: sam.address, privateKey: "" },
        attacker: { address: attacker.address, privateKey: "" },
        benignRecipient: benignRecipient.address,
      },
    });
    const target = writeFrontendConfig(cfg);
    console.log("Insufficient Sepolia funds for on-chain deployment. Switched to simulation config.");
    console.log("Frontend config written:", target);
    return;
  }

  try {
    await (await deployer.sendTransaction({ to: alex.address, value: fundingAmount })).wait();
    await (await deployer.sendTransaction({ to: sam.address, value: fundingAmount })).wait();

    await waitForEth(provider, alex.address);
    await waitForEth(provider, sam.address);

    const alexSigner = alex.connect(provider);
    const samSigner = sam.connect(provider);

    const MockUSDC = await ethers.getContractFactory("MockUSDC");
    const AttackSimulator = await ethers.getContractFactory("AttackSimulator");
    const AgentGuardOnChain = await ethers.getContractFactory("AgentGuardOnChain");

    const mockUsdc = await MockUSDC.deploy();
    await mockUsdc.waitForDeployment();

    const attackSimulator = await AttackSimulator.deploy();
    await attackSimulator.waitForDeployment();

    const agentGuardOnChain = await AgentGuardOnChain.deploy();
    await agentGuardOnChain.waitForDeployment();

    const mockUsdcAddress = await mockUsdc.getAddress();
    const attackSimulatorAddress = await attackSimulator.getAddress();
    const agentGuardAddress = await agentGuardOnChain.getAddress();

    const initialAmount = ethers.parseUnits("50", 6);
    const drainAmount = ethers.parseUnits("20", 6);

    await (await mockUsdc.mint(alex.address, initialAmount)).wait();
    await (await mockUsdc.mint(sam.address, initialAmount)).wait();

    const alexToken = mockUsdc.connect(alexSigner);
    const samToken = mockUsdc.connect(samSigner);

    await (await alexToken.approve(attackSimulatorAddress, ethers.MaxUint256)).wait();
    await (await samToken.approve(agentGuardAddress, ethers.MaxUint256)).wait();

    const samGuard = agentGuardOnChain.connect(samSigner);
    await (await samGuard.approveIntent(mockUsdcAddress, benignRecipient.address, drainAmount)).wait();

    const cfg = buildConfig({
      mode: "onchain",
      deployerAddress: deployer.address,
      deployerBalanceEth: ethers.formatEther(deployerBalance),
      minRequiredBalanceEth: ethers.formatEther(minRequiredBalance),
      walletFundingEth,
      contracts: {
        mockUsdc: mockUsdcAddress,
        attackSimulator: attackSimulatorAddress,
        agentGuardOnChain: agentGuardAddress,
      },
      demoWallets: {
        alex: { address: alex.address, privateKey: alex.privateKey },
        sam: { address: sam.address, privateKey: sam.privateKey },
        attacker: { address: attacker.address, privateKey: attacker.privateKey },
        benignRecipient: benignRecipient.address,
      },
    });

    const frontendConfigPath = writeFrontendConfig(cfg);

    console.log("\n--- Live Attack Demo Deployment Summary ---");
    console.log("MockUSDC:", mockUsdcAddress);
    console.log("AttackSimulator:", attackSimulatorAddress);
    console.log("AgentGuardOnChain:", agentGuardAddress);
    console.log("Alex:", alex.address);
    console.log("Sam:", sam.address);
    console.log("Attacker:", attacker.address);
    console.log("Benign Recipient:", benignRecipient.address);
    console.log("Frontend config written:", frontendConfigPath);
  } catch (error) {
    const msg = String(error?.message || "").toLowerCase();
    if (msg.includes("insufficient funds")) {
      const cfg = buildConfig({
        mode: "simulation",
        simulationReason: "insufficient_funds",
        deployerAddress: deployer.address,
        deployerBalanceEth: ethers.formatEther(deployerBalance),
        minRequiredBalanceEth: ethers.formatEther(minRequiredBalance),
        walletFundingEth,
        demoWallets: {
          alex: { address: alex.address, privateKey: "" },
          sam: { address: sam.address, privateKey: "" },
          attacker: { address: attacker.address, privateKey: "" },
          benignRecipient: benignRecipient.address,
        },
      });
      const target = writeFrontendConfig(cfg);
      console.log("Insufficient Sepolia funds for on-chain deployment. Switched to simulation config.");
      console.log("Frontend config written:", target);
      return;
    }
    throw error;
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
