// Auto-generated by contracts/scripts/deployDemo.js
export const DEMO_CONFIG = {
  "mode": "onchain",
  "simulationReason": "",
  "deployerAddress": "0x1086fFB85360eDBF6C47eA4Ba5e64CeC505faE8b",
  "deployerBalanceEth": "0.003637858759885636",
  "minRequiredBalanceEth": "0.0022",
  "walletFundingEth": "0.00035",
  "rpcUrl": "https://gateway.tenderly.co/public/sepolia",
  "chainId": 11155111,
  "explorerBaseUrl": "https://sepolia.etherscan.io/tx/",
  "contracts": {
    "mockUsdc": "0xe40AE88C5d599E0aD3C3934616eB0BeD87313105",
    "attackSimulator": "0x70ca779C27c320De1aB773B43f19D8986cC8787a",
    "agentGuardOnChain": "0x334fFB19a7e035ada5064364E0230069323213DF"
  },
  "demoWallets": {
    "alex": {
      "address": "0x651852851E5c279fdBCC7189C1aBc5d78E7aeDE9",
      "privateKey": "0x81ed72de2bba092e3c9fd4b9e99020e6404a757617090cbbcabef6476a00d528"
    },
    "sam": {
      "address": "0xBFdFa8E3f18c68038B1c82A68F9C78095915B6DC",
      "privateKey": "0x9f2d587572ff872b1205412630b587c229f7d84d62720c2f8ff0e667b5a4446a"
    },
    "attacker": {
      "address": "0x4Aa2E77b9CAc1412E36655cD438f208F6CA4Ab7B",
      "privateKey": "0xa2a2b3b3860e1bf0ab597c3ac5272bf35bfb19d6b359d66c7f9ddca25d9557be"
    },
    "benignRecipient": "0x4274F2E230040f83cCd2d12Ee1666b3beaCfD44C"
  },
  "initialAmount": "50",
  "drainAmount": "20",
  "tokenDecimals": 6
};

export const ATTACK_SIMULATOR_ABI = [
  "function drainWallet(address token,address victim,address to,uint256 amount) external",
];

export const AGENT_GUARD_ONCHAIN_ABI = [
  "function approveIntent(address token,address to,uint256 amount) external",
  "function validateAndExecute(address token,address to,uint256 amount) external",
  "function intentHashOf(address user) external view returns (bytes32)",
];

export const MOCK_USDC_ABI = [
  "function balanceOf(address account) external view returns (uint256)",
  "function allowance(address owner,address spender) external view returns (uint256)",
  "function approve(address spender,uint256 amount) external returns (bool)",
  "function decimals() external view returns (uint8)",
];
