// Auto-generated by contracts/scripts/deployDemo.js
export const DEMO_CONFIG = {
  "mode": "simulation",
  "simulationReason": "insufficient_funds",
  "rpcUrl": "https://gateway.tenderly.co/public/sepolia",
  "chainId": 11155111,
  "explorerBaseUrl": "https://sepolia.etherscan.io/tx/",
  "contracts": {
    "mockUsdc": "",
    "attackSimulator": "",
    "agentGuardOnChain": ""
  },
  "demoWallets": {
    "alex": {
      "address": "0xC4D9b350DC6Da22583d0d07F08491f616e825Dc5",
      "privateKey": ""
    },
    "sam": {
      "address": "0x1F390Af8acF7054454499Cc98e76175cd2353072",
      "privateKey": ""
    },
    "attacker": {
      "address": "0xA272dc40af5E6ffcb0956518212cb20E6B12aD74",
      "privateKey": ""
    },
    "benignRecipient": "0xF9DDa9A51ede5F84B72ee950BE860f7B975cFCb7"
  },
  "initialAmount": "50",
  "drainAmount": "20",
  "tokenDecimals": 6
};

export const ATTACK_SIMULATOR_ABI = [
  "function drainWallet(address token,address victim,address to,uint256 amount) external",
];

export const AGENT_GUARD_ONCHAIN_ABI = [
  "function approveIntent(address token,address to,uint256 amount) external",
  "function validateAndExecute(address token,address to,uint256 amount) external",
  "function intentHashOf(address user) external view returns (bytes32)",
];

export const MOCK_USDC_ABI = [
  "function balanceOf(address account) external view returns (uint256)",
  "function allowance(address owner,address spender) external view returns (uint256)",
  "function approve(address spender,uint256 amount) external returns (bool)",
  "function decimals() external view returns (uint8)",
];
